### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
### Libraries USed Tensorflow> 2.0  and keras

In [2]:
tf.__version__

<IPython.core.display.Javascript object>

'1.13.1'

In [3]:
##tensorflow >2.0
from keras.preprocessing.text import one_hot

Using TensorFlow backend.


In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### Vocabulary size
voc_size=10000

In [7]:
for words in sent:
    print(words)

the glass of milk
the glass of juice
the cup of tea
I am a good boy
I am a good developer
understand the meaning of words
your videos are good


#### One Hot Representation

In [8]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[1606, 1146, 8877, 8560], [1606, 1146, 8877, 9425], [1606, 7702, 8877, 8855], [5592, 5232, 1126, 8341, 4147], [5592, 5232, 1126, 8341, 1600], [4597, 1606, 589, 8877, 3538], [9658, 9964, 289, 8341]]


### Word Embedding Represntation

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1606 1146 8877 8560]
 [   0    0    0    0 1606 1146 8877 9425]
 [   0    0    0    0 1606 7702 8877 8855]
 [   0    0    0 5592 5232 1126 8341 4147]
 [   0    0    0 5592 5232 1126 8341 1600]
 [   0    0    0 4597 1606  589 8877 3538]
 [   0    0    0    0 9658 9964  289 8341]]


In [12]:
dim=10

In [13]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.


In [14]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [15]:
print(model.predict(embedded_docs))

[[[-1.99611429e-02 -1.47078857e-02  6.57491758e-03  3.42331566e-02
    2.55543925e-02 -9.75931808e-03 -2.67485268e-02  6.78088516e-03
    4.76816185e-02  2.87937038e-02]
  [-1.99611429e-02 -1.47078857e-02  6.57491758e-03  3.42331566e-02
    2.55543925e-02 -9.75931808e-03 -2.67485268e-02  6.78088516e-03
    4.76816185e-02  2.87937038e-02]
  [-1.99611429e-02 -1.47078857e-02  6.57491758e-03  3.42331566e-02
    2.55543925e-02 -9.75931808e-03 -2.67485268e-02  6.78088516e-03
    4.76816185e-02  2.87937038e-02]
  [-1.99611429e-02 -1.47078857e-02  6.57491758e-03  3.42331566e-02
    2.55543925e-02 -9.75931808e-03 -2.67485268e-02  6.78088516e-03
    4.76816185e-02  2.87937038e-02]
  [-5.97156584e-04  4.65418212e-02  3.74025144e-02 -3.64688858e-02
    2.74803378e-02 -1.85243264e-02 -4.87956069e-02  1.66582130e-02
   -7.15889782e-03  4.84144352e-02]
  [ 1.29713863e-03 -1.52390711e-02  3.00120749e-02  1.60244741e-02
   -4.69399095e-02 -3.86990197e-02  1.95960291e-02 -1.76180005e-02
   -6.64841011e-

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 1606, 1146, 8877, 8560])

In [17]:
print(model.predict(embedded_docs)[0])

[[-0.01996114 -0.01470789  0.00657492  0.03423316  0.02555439 -0.00975932
  -0.02674853  0.00678089  0.04768162  0.0287937 ]
 [-0.01996114 -0.01470789  0.00657492  0.03423316  0.02555439 -0.00975932
  -0.02674853  0.00678089  0.04768162  0.0287937 ]
 [-0.01996114 -0.01470789  0.00657492  0.03423316  0.02555439 -0.00975932
  -0.02674853  0.00678089  0.04768162  0.0287937 ]
 [-0.01996114 -0.01470789  0.00657492  0.03423316  0.02555439 -0.00975932
  -0.02674853  0.00678089  0.04768162  0.0287937 ]
 [-0.00059716  0.04654182  0.03740251 -0.03646889  0.02748034 -0.01852433
  -0.04879561  0.01665821 -0.0071589   0.04841444]
 [ 0.00129714 -0.01523907  0.03001207  0.01602447 -0.04693991 -0.03869902
   0.01959603 -0.017618   -0.00664841  0.01479392]
 [-0.0394518   0.01100974  0.00106493 -0.01419612  0.03209748  0.02130302
   0.01494594  0.00572605  0.02898667  0.00782245]
 [-0.02963016  0.037719    0.01190646 -0.04856114  0.04765617  0.0123377
  -0.04060105  0.02558053 -0.03972328 -0.02712086]]
